### ISSUE TITLE
[Bug] bubop - Not enough arguments provided

### ISSUE THREAD

**Issue by Petemir** [bergercookie/taskwarrior-syncall#37]
Trying to launch the latest version of the software fails.

System: 
* python v3.8.8
* KUbuntu 21.10

Steps to follow:
* `pip3 install --user git+https://github.com/bergercookie/taskwarrior-syncall`
(FYI, it installs bubop 0.1.6a)

* `~/.local/bin/tw_gcal_sync -c "GCAL_CALENDAR" -t "TW_TAG"`

I get the following error:
```
Traceback (most recent call last):
  File "/home/petemir/.local/bin/tw_gcal_sync", line 11, in <module>
    sys.exit(main())
  File "/home/petemir/Apps/anaconda3/envs/newbase/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/petemir/Apps/anaconda3/envs/newbase/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/petemir/Apps/anaconda3/envs/newbase/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/petemir/Apps/anaconda3/envs/newbase/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/petemir/.local/lib/python3.8/site-packages/taskwarrior_syncall/scripts/tw_gcal_sync.py", line 88, in main
    check_required_mutually_exclusive(combination_name, custom_combination_savename)
  File "/home/petemir/.local/lib/python3.8/site-packages/bubop/cli.py", line 30, in check_required_mutually_exclusive
    raise NotEnoughArgumentsError()
bubop.exceptions.NotEnoughArgumentsError: Not enough arguments provided
```

Deleting lines 88-98 lets me run the program, but obviously, I would be missing some kind of additional validation.

Thanks!

**Comment by bergercookie** [comment]
Hi @Petemir , can you test with the devel branch? it should be fixed there.

**Comment by bergercookie** [comment]
Should also be available in the latest pre-release: `pip install taskwarrior-syncall==1.2.0b2`

**Comment by Petemir** [comment]
@bergercookie now it works great, thanks!
