### ISSUE TITLE
[BUG] Google Keep sync fails with BadAuthentication

### ISSUE THREAD

**Issue by PMunch** [bergercookie/taskwarrior-syncall#54]
### Describe the bug

Recently updated my Ubuntu server and after the update the taskwarrior_syncall library was gone. Just got this error when running `tw_gkeep_sync` (which for some reason was still installed):

```
Traceback (most recent call last):
  File "/home/taskwarrior/.local/bin/tw_gkeep_sync", line 5, in <module>
    from taskwarrior_syncall.scripts.tw_gkeep_sync import main
ModuleNotFoundError: No module named 'taskwarrior_syncall'
```

After reinstalling taskwarrior through pip3 (version 1.2.1) I'm getting `BadAuthentication` errors like this:

```
09:10:10.06 | ERROR    	| Application failed; Below you can find the error message and stack trace. If you think this is a bug, attach this stack trace to create a new issue -> [https://github.com/bergercookie/taskwarrior-syncall/issues].
Traceback (most recent call last):

  File "/home/taskwarrior/.local/bin/tw_gkeep_sync", line 8, in <module>
    sys.exit(main())
    │   │    └ <Command main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/taskwarrior/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fe3e2f67a30>
           └ <Command main>
  File "/home/taskwarrior/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fe3e3f0fcd0>
         │    └ <function Command.invoke at 0x7fe3e2f7c550>
         └ <Command main>
  File "/home/taskwarrior/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'tw_tags': ('groceries',), 'gkeep_note': 'Redacted', 'verbose': 1, 'gkeep_user_pass_path': 'gkeepapi/user', 'gkeep_pass...
           │   │      │    │           └ <click.core.Context object at 0x7fe3e3f0fcd0>
           │   │      │    └ <function main at 0x7fe3e238ba30>
           │   │      └ <Command main>
           │   └ <function Context.invoke at 0x7fe3e2f67250>
           └ <click.core.Context object at 0x7fe3e3f0fcd0>
  File "/home/taskwarrior/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'tw_tags': ('groceries',), 'gkeep_note': 'Redacted', 'verbose': 1, 'gkeep_user_pass_path': 'gkeepapi/user', 'gkeep_pass...
                       └ ()
> File "/home/taskwarrior/.local/lib/python3.10/site-packages/taskwarrior_syncall/scripts/tw_gkeep_sync.py", line 178, in main
    with Aggregator(
         └ <class 'taskwarrior_syncall.aggregator.Aggregator'>
  File "/home/taskwarrior/.local/lib/python3.10/site-packages/taskwarrior_syncall/aggregator.py", line 121, in __enter__
    self.start()
    │    └ <function Aggregator.start at 0x7fe3e313dbd0>
    └ <taskwarrior_syncall.aggregator.Aggregator object at 0x7fe3e2383a60>
  File "/home/taskwarrior/.local/lib/python3.10/site-packages/taskwarrior_syncall/aggregator.py", line 203, in start
    self._side_A.start()
    │    │       └ <function GKeepTodoSide.start at 0x7fe3e238a830>
    │    └ <taskwarrior_syncall.google.gkeep_todo_side.GKeepTodoSide object at 0x7fe3e23811b0>
    └ <taskwarrior_syncall.aggregator.Aggregator object at 0x7fe3e2383a60>
  File "/home/taskwarrior/.local/lib/python3.10/site-packages/taskwarrior_syncall/google/gkeep_todo_side.py", line 56, in start
    success = self._keep.login(self._gkeep_user, self._gkeep_passwd)
              │    │     │     │    │            │    └ 'Redacted password'
              │    │     │     │    │            └ <taskwarrior_syncall.google.gkeep_todo_side.GKeepTodoSide object at 0x7fe3e23811b0>
              │    │     │     │    └ 'Redacted mail'
              │    │     │     └ <taskwarrior_syncall.google.gkeep_todo_side.GKeepTodoSide object at 0x7fe3e23811b0>
              │    │     └ <function Keep.login at 0x7fe3e2389240>
              │    └ <gkeepapi.Keep object at 0x7fe3e23ec7c0>
              └ <taskwarrior_syncall.google.gkeep_todo_side.GKeepTodoSide object at 0x7fe3e23811b0>
  File "/home/taskwarrior/.local/lib/python3.10/site-packages/gkeepapi/__init__.py", line 695, in login
    ret = auth.login(username, password, device_id)
          │    │     │         │         └ 125331095410741
          │    │     │         └ 'Redacted password'
          │    │     └ 'Redacted mail'
          │    └ <function APIAuth.login at 0x7fe3e2388040>
          └ <gkeepapi.APIAuth object at 0x7fe3e23ed540>
  File "/home/taskwarrior/.local/lib/python3.10/site-packages/gkeepapi/__init__.py", line 59, in login
    raise exception.LoginException(
          │         └ <class 'gkeepapi.exception.LoginException'>
          └ <module 'gkeepapi.exception' from '/home/taskwarrior/.local/lib/python3.10/site-packages/gkeepapi/exception.py'>

gkeepapi.exception.LoginException: ('BadAuthentication', None)
```

The username and password works just fine in the browser. I also tried to enable 2-factor authentication and create an application password but still no dice. Also tried to upgrade all the pip packages, but taskwarrior is apparently locked at older versions of some packages.

### To Reproduce

Try to sync with GKeep

### Expected Behavior

Everything should work like it did before I upgraded Ubuntu.

#### OS Version (`cat /etc/*-release; uname -a`)

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
Linux ubuntu 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

#### Python version (`python --version; python3 --version`)

Python 3.10.4

#### `--version` of your executable

`tw_gkeep_sync, version 1.2.1`

**Comment by bergercookie** [comment]
This should now be fixed. Please download the latest version of this repo (renamed to syncall instead of taskwarrior-syncall) and if it's still there, we can reopen this.

**Comment by oneacik** [comment]
1.5.1 seems also to be affected
