### ISSUE TITLE
[BUG] "include" in TW config file crashes taskwarrior-syncall

### ISSUE THREAD

**Issue by amiroslaw** [bergercookie/taskwarrior-syncall#57]
Taskwarrior allows to include theme or external config file (it's great to store sync configuration in different location). With those configuration taskwarrior-syncall crashes. 

### To Reproduce
In .taskrc
include light-16.theme
include ~/task/wingtask

### Error
```
Traceback (most recent call last):
  File "/home/miro/.local/bin/tw_gcal_sync", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/miro/.local/lib/python3.10/site-packages/taskwarrior_syncall/scripts/tw_gcal_sync.py", line 142, in main
    tw_side = TaskWarriorSide(tags=tw_tags, project=tw_project)
  File "/home/miro/.local/lib/python3.10/site-packages/taskwarrior_syncall/taskwarrior_side.py", line 53, in __init__
    self._tw = TaskWarrior(marshal=True, config_filename=config_file)
  File "/home/miro/.local/lib/python3.10/site-packages/taskw/warrior.py", line 438, in __init__
    super(TaskWarriorShellout, self).__init__(config_filename)
  File "/home/miro/.local/lib/python3.10/site-packages/taskw/warrior.py", line 62, in __init__
    self.config = TaskWarriorBase.load_config(config_filename)
  File "/home/miro/.local/lib/python3.10/site-packages/taskw/warrior.py", line 180, in load_config
    return TaskRc(config_filename, overrides=overrides)
  File "/home/miro/.local/lib/python3.10/site-packages/taskw/taskrc.py", line 58, in __init__
    config = self._read(self.path)
  File "/home/miro/.local/lib/python3.10/site-packages/taskw/taskrc.py", line 106, in _read
    TaskRc(right.strip())
  File "/home/miro/.local/lib/python3.10/site-packages/taskw/taskrc.py", line 58, in __init__
    config = self._read(self.path)
  File "/home/miro/.local/lib/python3.10/site-packages/taskw/taskrc.py", line 96, in _read
    with codecs.open(path, 'r', 'utf8') as config_file:
  File "/usr/lib/python3.10/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'light-16.theme'
```

**Comment by bergercookie** [comment]
Pending PR in taskw that fixes this: https://github.com/ralphbean/taskw/pull/151

**Comment by bergercookie** [comment]
The `taskw` repo doesn't seem to be in active development anymore and thus, the PR above is not merged yet. We should either fork and push our own versions of `taskw` or, alternatively, switch to `tasklib` (see https://github.com/bergercookie/syncall/issues/65).
